<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>WinExe</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<StartupObject>CalendarSync.Program</StartupObject>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<ApplicationIcon>ico\cal64.ico</ApplicationIcon>
		<PlatformTarget>x86</PlatformTarget>

		<OutputPath>Z:\Calendar\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Ical.Net" Version="5.0.0-pre.41" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Serilog" Version="4.2.0" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="9.0.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
		<COMReference Include="Microsoft.Office.Interop.Outlook">
			<WrapperTool>tlbimp</WrapperTool>
			<VersionMajor>9</VersionMajor>
			<VersionMinor>6</VersionMinor>
			<Guid>00062fff-0000-0000-c000-000000000046</Guid>
			<Lcid>0</Lcid>
			<Isolated>false</Isolated>
			<EmbedInteropTypes>true</EmbedInteropTypes>
		</COMReference>
	</ItemGroup>

	<ItemGroup>
		<None Include="build\Readme.txt" Condition="'$(Configuration)'=='Release'">
			<TargetPath>Readme.txt</TargetPath>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Include="build\config.json">
			<TargetPath>config.json</TargetPath>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="ico\*.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="RelocateDlls" AfterTargets="Build">
		<ItemGroup>
			<RootDlls Include="$(OutputPath)*.dll"
					  Exclude="
						$(OutputPath)bin\**;
						$(OutputPath)$(AssemblyName).dll" />
			<RuntimeDlls Include="$(OutputPath)runtimes\win\lib\net8.0\*.dll" />
			<RuntimeDirsToPrune Include="
				$(OutputPath)runtimes\win\lib\net8.0;
				$(OutputPath)runtimes\win\lib;
				$(OutputPath)runtimes\win;
				$(OutputPath)runtimes" />
		</ItemGroup>

		<MakeDir Directories="$(OutputPath)bin\" />

		<Copy SourceFiles="@(RootDlls)"
			  DestinationFolder="$(OutputPath)bin\"
			  SkipUnchangedFiles="true"
			  Condition="@(RootDlls->Count()) != 0" />
		<Delete Files="@(RootDlls)" Condition="@(RootDlls->Count()) != 0" />

		<Copy SourceFiles="@(RuntimeDlls)"
			  DestinationFolder="$(OutputPath)bin\"
			  SkipUnchangedFiles="true"
			  Condition="@(RuntimeDlls->Count()) != 0" />
		<Delete Files="@(RuntimeDlls)" Condition="@(RuntimeDlls->Count()) != 0" />

		<RemoveDir Directories="@(RuntimeDirsToPrune)"
				   Condition="Exists('%(RuntimeDirsToPrune.Identity)')" />
	</Target>

</Project>
